---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Enabling Replication on two S3 buckets in the same AWS Account
Parameters:
  ID:
    Description: your unique ID or name
    Type: String
Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "source-bucket-${ID}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      ReplicationConfiguration:
        Role: !GetAtt "ReplicationRole.Arn"
        Rules:
          - Destination:
              Bucket: "arn:aws:s3:::destination-bucket-${ID}"
              StorageClass: STANDARD
            Id: ReplicationConfig
            Prefix: ""
            Status: Enabled

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "destination-bucket-${ID}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ReplicationPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetReplicationConfiguration"
              - "s3:ListBucket"
            Effect: Allow
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::source-bucket-${ID}"
          - Action:
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionAcl"
            Effect: Allow
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::source-bucket-${ID}/*"
          - Action:
              - "s3:ReplicateObject"
              - "s3:ReplicateDelete"
            Effect: Allow
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::destination-bucket-${ID}/*"
      PolicyName: ReplicationPolicy
      Roles:
        - !Ref ReplicationRole

  ReplicationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
